#!/bin/bash

# Detener si hay errores
set -e

echo "--- SETUP ARK ---"

# 1. Limpieza
echo "[Setup] Limpiando directorios..."
rm -rf bin build
mkdir -p bin build

# 2. Compilar el propio compilador Ark
echo "[Setup] Compilando Ark (C++)..."
g++ -std=c++17 src/*.cpp -o build/ark

# 3. Usar Ark para compilar el ejemplo
# (Aqui main.cpp se encarga de llamar a NASM y LD)
echo "[Setup] Ejecutando Ark sobre examples/code.ark..."
./build/ark examples/code.ark

# 4. Si todo salio bien, correr el programa final
if [ -f "bin/output" ]; then
    echo ""
    echo "--- EJECUTANDO PROGRAMA DE USUARIO ---"
    echo "--------------------------------------"
    ./bin/output
    echo ""
    echo "--------------------------------------"
else
    echo "[Setup] Error: No se encontro el ejecutable final."
    exit 1
fi