#!/bin/bash

# Parar si hay errores
set -e

echo "--- LIMPIEZA PROFUNDA ---"
rm -rf bin build
mkdir -p bin build

echo "1. Compilando el Compilador (C++)..."
g++ -std=c++17 src/*.cpp -o build/ark

echo "2. Ejecutando Ark sobre examples/code.ark..."
./build/ark examples/code.ark

echo "3. Ensamblando con NASM..."
nasm -f elf64 bin/output.asm -o bin/output.o

echo "4. Linkeando..."
ld bin/output.o -o bin/output

echo "--- EJECUTANDO PROGRAMA FINAL ---"
echo "---------------------------------"
./bin/output
echo ""
echo "---------------------------------"